### ISSUE TITLE
 The collection does not contain any Nodes

### ISSUE THREAD

**Issue by charbel** [bissolli/twitter-php-scraper#5]
```
<?php
require __DIR__ . '/vendor/autoload.php';

$twitter = new \Bissolli\TwitterScraper\Twitter('official_php');
var_dump($twitter->getProfile());

?>
```

**Fatal error**:  Uncaught PHPHtmlParser\Exceptions\EmptyCollectionException: The collection does not contain any Nodes. in .\vendor\paquettg\php-html-parser\src\PHPHtmlParser\Dom\Collection.php:40
Stack trace:
#0 .\vendor\bissolli\twitter-php-scraper\src\Twitter.php(45): PHPHtmlParser\Dom\Collection->__call('find', Array)
#1 .\vendor\bissolli\twitter-php-scraper\src\Twitter.php(29): Bissolli\TwitterScraper\Twitter->extractProfileCard()
#2 test.php(5): Bissolli\TwitterScraper\Twitter->__construct('official_php')
#3 {main}
  thrown **in vendor\paquettg\php-html-parser\src\PHPHtmlParser\Dom\Collection.php on line 40**

**Comment by jacmaes** [comment]
Same error for me.

**Comment by fers4t** [comment]
same here

**Comment by JacobDB** [comment]
Did y'all ever figure this out? Running in to the same issue...
